from flask_restful import reqparse

parser = reqparse.RequestParser()
parser.add_argument('age', required=True, type=int)
parser.add_argument('surname', required=True)
parser.add_argument('name', required=True)
parser.add_argument('speciality', required=True)
parser.add_argument('email', required=True)
parser.add_argument('about', required=False)
parser.add_argument('avatar_url', required=False)
parser.add_argument('password', required=True)
job_parser = reqparse.RequestParser()
job_parser.add_argument('author', required=False, type=int)
job_parser.add_argument('requirements', required=True)
job_parser.add_argument('description', required=True)
job_parser.add_argument('header', required=True)
job_parser.add_argument('form', required=False)
message_parser = reqparse.RequestParser()
message_parser.add_argument('sender', required=False, type=int)
message_parser.add_argument('receiver', required=False, type=int)
message_parser.add_argument('text', required=False)
